# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K738pxgVRy5dXV0N1lC6BQh_HKsarXx2
"""

import sys
import joblib
import pandas as pd
import json
import warnings
warnings.filterwarnings("ignore")
model = joblib.load('cds_model.pkl')
difficulty = int(sys.argv[1])
english = int(sys.argv[2])
gk = int(sys.argv[3])
maths = int(sys.argv[4])
total = english + gk + maths
ota_total = english + gk
columns = ['Difficulty_level', 'English_Marks', 'GK_Marks', 'Maths_Marks', 'Total_Marks', 'OTA_Total_Marks']

def predict(difficulty, english, gk, maths):
    total = english + gk + maths
    ota_total = english + gk

    df = pd.DataFrame([[difficulty, english, gk, maths, total, ota_total]], columns=columns)
    probs = model.predict_proba(df)
    return {
        "IMA": int(probs[0][0][1]*100),
        "INA": int(probs[1][0][1]*100),
        "AFA": int(probs[2][0][1]*100),
        "OTA": int(probs[3][0][1]*100)
    }
base = predict(difficulty, english, gk, maths)
cutoffs = {"IMA":130, "INA":118, "AFA":140, "OTA":90}
status = {
    "IMA": "Safe" if total >= cutoffs["IMA"] else "Risky",
    "INA": "Safe" if total >= cutoffs["INA"] else "Risky",
    "AFA": "Safe" if total >= cutoffs["AFA"] else "Risky",
    "OTA": "Safe" if ota_total >= cutoffs["OTA"] else "Risky"
}
maths_boost = predict(difficulty, english, gk, maths+10)
english_boost = predict(difficulty, english+10, gk, maths)
gk_boost = predict(difficulty, english, gk+10, maths)
improvement = {
    "Maths": maths_boost["IMA"] - base["IMA"],
    "English": english_boost["IMA"] - base["IMA"],
    "GK": gk_boost["IMA"] - base["IMA"]
}
result = {
    **base,
    "cutoffs": cutoffs,
    "status": status,
    "improvement": improvement
}
print(json.dumps(result))
